export const data  = [
    {
        question: "What is the most abundant gas in the Earth's atmosphere?",
        option1: "Oxygen",
        option2: "Hydrogen",
        option3: "Carbon Dioxide",
        option4: "Nitrogen",
        ans: 4,
    },
    {
        question: "What is the chemical symbol for gold?",
        option1: "Au",
        option2: "Ag",
        option3: "Fe",
        option4: "Gd",
        ans: 1,
    },
    {
        question: "Which element is known as the 'King of Chemicals'?",
        option1: "Oxygen",
        option2: "Hydrogen",
        option3: "Sulfuric Acid",
        option4: "Helium",
        ans: 3,
    },
    {
        question: "What is the main component of natural gas?",
        option1: "Methane",
        option2: "Ethane",
        option3: "Propane",
        option4: "Butane",
        ans: 1,
    },
    {
        question: "Which acid is commonly found in car batteries?",
        option1: "Hydrochloric Acid",
        option2: "Sulfuric Acid",
        option3: "Nitric Acid",
        option4: "Acetic Acid",
        ans: 2,
    },
    {
        question: "What is the pH level of pure water at 25°C?",
        option1: "7",
        option2: "5",
        option3: "9",
        option4: "3",
        ans: 1,
    },
    {
        question: "Which element has the highest electronegativity?",
        option1: "Oxygen",
        option2: "Fluorine",
        option3: "Chlorine",
        option4: "Bromine",
        ans: 2,
    },
    {
        question: "What type of bond is formed when electrons are shared between atoms?",
        option1: "Ionic Bond",
        option2: "Covalent Bond",
        option3: "Metallic Bond",
        option4: "Hydrogen Bond",
        ans: 2,
    },
    {
        question: "Which substance is used as a moderator in nuclear reactors?",
        option1: "Plutonium",
        option2: "Uranium",
        option3: "Graphite",
        option4: "Lead",
        ans: 3,
    },
    {
        question: "What is the common name for dihydrogen monoxide?",
        option1: "Salt",
        option2: "Sugar",
        option3: "Water",
        option4: "Vinegar",
        ans: 3,
    }
];
